### ISSUE TITLE
Variable misnamed in core.py

### ISSUE THREAD

**Issue by lirainer** [EPAENERGYSTAR/epathermostat#18]
The `RESISTANCE_HEAT_USE_BIN_TUPLE_FIRST ` variable is assigned at [line 38 of core.py](https://github.com/EPAENERGYSTAR/epathermostat/blob/68826365a2e23dc757f2dcc7837f3aca18ce9094/thermostat/core.py#L38) but referenced at [line 1595](https://github.com/EPAENERGYSTAR/epathermostat/blob/68826365a2e23dc757f2dcc7837f3aca18ce9094/thermostat/core.py#L1595) as `RESISTANCE_HEAT_USE_BIN_FIRST_TUPLE `.

I assume this has not shown up as an error since `rhu_first` has never been `None`.

### Solution
rename to `RESISTANCE_HEAT_USE_BIN_FIRST_TUPLE `

**Comment by craigmaloney** [comment]
This has been fixed in 1.7.1 and been removed in 2.0. Thanks!
