### ISSUE TITLE
Wrong column label in Output file documentation

### ISSUE THREAD

**Issue by lirainer** [EPAENERGYSTAR/epathermostat#23]
@craigmaloney In the [Output data documentation](https://github.com/EPAENERGYSTAR/epathermostat/blob/feature/epathermostat_2.0/docs/data_files.rst#output-data), `end_zone` should be `end_date` (to match what is in [exporters.py](https://github.com/EPAENERGYSTAR/epathermostat/blob/feature/epathermostat_2.0/thermostat/exporters.py#L17)).

**Comment by craigmaloney** [comment]
Good catch (no pun intended). Thanks!
