### ISSUE TITLE
Update climate zone weighting factors

### ISSUE THREAD

**Issue by lirainer** [EPAENERGYSTAR/epathermostat#43]
Climate zone weighting factors have been updated using RECS 2020 data (see [this](https://docs.google.com/spreadsheets/d/1cr69XAkUSMtzrHL6yra3kkOi1ekHgJGNYFy0huO3uVw/edit#gid=515711632) google sheet for calculations).

New weights:

Climate Zone | Heating | Cooling
-- | -- | --
Very cold and Cold | 56.4% | 19.4%
Mixed-humid | 29.4% | 31.1%
Mixed-dry and Hot-dry | 5.1% | 13.7%
Hot-humid | 5.4% | 34.5%
Marine | 3.7% | 1.3%

Update [NationalAverageClimateZoneWeightings.csv](https://github.com/EPAENERGYSTAR/epathermostat/blob/master/thermostat/resources/NationalAverageClimateZoneWeightings.csv) and change the code in [climate_zone.py](https://github.com/EPAENERGYSTAR/epathermostat/blob/f98a8954a1add8c7e4b62f1d139328a304e686e4/thermostat/climate_zone.py) to use the file instead of the inline data at line 42.

**Comment by john-zither** [comment]
I havent managed to fix the issue with us being unable to assign or reference each other @lirainer however, I have put up a [PR with these changes](https://github.com/EPAENERGYSTAR/epathermostat/pull/45)

If possible, could you suggest any key edge cases to check for the ```retrieve_climate_zone``` function in [climate_zone.py](https://github.com/EPAENERGYSTAR/epathermostat/blob/feature/epa2.0_climate_zone_weights/thermostat/climate_zone.py#L50), I noticed this part of the code was untested.
